#!/bin/bash

function lxc-root {
lxc exec $1 bash
}

function lxc-daemon-start {
lxc exec $1 systemctl start $1
}

function lxc-daemon-log {
lxc exec $1 -- journalctl -u $1 -f -ocat
}

function lxc-ram {
if [ $1 == "all" ]
then
  LIST=($(lxc list -c n -f csv))
  for x in "${LIST[@]}"
  do
    echo -e "\e[1m\e[94m[\e[90m${x}\e[94m]\e[0m"
    DATA=$(lxc exec $x -- free -h)
    echo $DATA | head | awk '{printf $1" "$2" \033[33m"$6"\n\033[0m"$8" "$9" \033[33m"$13"\033[0m\n"}'
  done
else
  echo -e "\e[1m\e[94m[\e[90m$1\e[94m]\e[0m"
  DATA=$(lxc exec $1 -- free -h)
  echo $DATA | head | awk '{printf $1" "$2" \033[33m"$6"\n\033[0m"$8" "$9" \033[33m"$13"\033[0m\n"}'
fi
}

`function lxc-logs {
LIST=($(lxc list -c n,image.os:os -f csv))
for x in "${LIST[@]}"
do
i=(${x//,/ })
if [[ ${i[1]} == "Debian" ]] || [[ ${i[1]} == "Ubuntu" ]]
then
echo -e "clearing logs for \e[31m\e[1m${i[0]}\e[0m"
lxc exec ${i[0]} -- sh -c "journalctl --vacuum-time=1d > /dev/null"
fi
done
}`

#list more info
alias list="lxc list -c nst,image.os:os,4u,config:limits.cpu:cpu,D,devices:root.size:DISK_limit,m,config:limits.memory:mem_limit,M"

#use with network/container name (should be the same)
alias login="lxc-root"
alias log="lxc-daemon-log"
alias start="lxc-daemon-start"
alias doreboot="sudo lxc stop --all && sudo reboot"
alias listautostart="/usr/local/bin/lxc-autostart-settings.sh"
alias ram="lxc-ram"
alias clear-logs="lxc-logs"
alias doupdate="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y"
alias doupdate-r="doupdate && doreboot"
