# my global config
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Scraping configuration
scrape_configs:
  - job_name: OpenWrt
    static_configs:
      - targets: ['<local ip>']
  - job_name: lxd
    metrics_path: '/1.0/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['<local ip>']
    tls_config:
      ca_file: 'tls/server.crt'
      cert_file: 'tls/metrics.crt'
      key_file: 'tls/metrics.key'
      server_name: 'nodev2'
  - job_name: 'machine-info'
    scrape_interval: 5s
    static_configs:
      -
        targets:
          - "localhost:9100"
        labels:
          instance: cserv
      -
        targets:
          - "<local ip>"
        labels:
          instance: node-host
  - job_name: 'nodes'
    static_configs:
      -
        targets:
          - "<local ip>"
        labels:
          network: coolcat
      -
        targets:
          - "<local ip>"
        labels:
          network: decentr
      -
        targets:
          - "<local ip>"
        labels:
          network: juno
      -
        targets:
          - "<local ip>"
        labels:
          network: nomic

  - job_name: 'caddy'
    metrics_path: "/scrape"
    scheme: "https"
    static_configs:
      - targets: ['cac-group.io']
#      -
#        targets:
#          - "cac-group.io"
#        labels:
#          instance:
#      -
#        targets:
#          - "rpc.juno.basementnodes.ca"
#        labels:
#          host: juno-rpc
